# Settings
baseurl = "https://photos.jaan.xyz/"
languageCode = "en-us"
title = "Photos - jaan.xyz"
theme = "phugo"

[params]

    # Meta
    description = "Photos by Jaan Toots"
    author = "Jaan Toots"
    keywords = "photogallery, photoblog, jaantoots, jaan toots"
    
    # Headerbar links
    # Do not put here too many links,
    # it will break mobile appearance

    [[params.header.links]]
    name = "About"
    url = "#footer"
    icon = "fa-info-circle"    
    
    # Footer panel
    
    [params.footer.paragraph]
    headline = "Gallery"
    text = "Mostly travel photography. All photos are available under a [Creative Commons Attribution-ShareAlike 4.0 International License](https://creativecommons.org/licenses/by-sa/4.0/). Contact me for original or better quality files.<br/> The source code for this site is available on [git.jaan.xyz](https://git.jaan.xyz) and [GitHub](https://github.com/jaantoots)."
    
    [params.footer.social]
    headline = "Find me"

    [[params.footer.social.links]]
    label = "Github"
    url = "https://github.com/jaantoots"
    icon = "fa-github"

    # Contact form
    
    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'realEmail' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    
    [params.footer.contact]
    realEmail = "jaan@photos.jaan.xyz"
    headline = "Get in touch"
    buttonText = "Send"
    resetText = "Reset"
    
    # 'warning' defines error messages for invalid inputs
    [params.footer.contact.name]
    text = "Name *"
    warning = "Please, enter your name"

    [params.footer.contact.email]
    text = "Email *"
    warning = "Please, enter your email."

    [params.footer.contact.message]
    text = "Message *"
    warning = "Please, enter your message"
    
    # Copyright
    [params.footer.copyright]
    name = "Jaan Toots. [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/)"
